# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:
  
  db:
    container_name: "db"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      #MYSQL_ROOT_PASSWORD: "root"
      #MYSQL_DATABASE: "symfony_docker"
      #MYSQL_USER: "root"
      #MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
 #   expose:
 #     - '3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
